bài 1

In [1]:
import numpy as np
print("Phiên bản NumPy:", np.__version__)
np.show_config()


Phiên bản NumPy: 2.3.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-nvpocyoj/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-nvpocyoj/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-nvpocyoj/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-nvpocyoj/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    open

bài 2


In [9]:
#1
import numpy as np
arr = np.array([0,1,2,3,4,5,6,6,7,8,9])
print(arr)  
print("Kiểu dữ liệu:", arr.dtype)
print("Kích thước shape:", arr.shape)
#2
arr_odd = arr[arr % 2 != 0]
arr_even = arr[arr % 2 == 0]

print("arr_odd =", arr_odd)
print("arr_even =", arr_even)
#3
arr_update = np.where(arr % 2 == 0, arr, 100)
print("arr_update =", arr_update)


[0 1 2 3 4 5 6 6 7 8 9]
Kiểu dữ liệu: int64
Kích thước shape: (11,)
arr_odd = [1 3 5 7 9]
arr_even = [0 2 4 6 6 8]
arr_update = [  0 100   2 100   4 100   6   6 100   8 100]


bài 3

In [8]:
#1
arr_a = np.array([1,2,3,2,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])
arr_c = np.intersect1d(arr_a, arr_b)
print("arr_c =", arr_c)
#2
arr_d = np.setdiff1d(arr_b, arr_a)
print("arr_d =", arr_d)
#3
arr_e = np.array([2,6,1,9,10,3,27,8,6,25,16])
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
print("arr_f =", arr_f)




arr_c = [2 4]
arr_d = [ 7  8  9 10]
arr_f = [ 6  9 10  8  6]


bài 4

In [7]:
import numpy as np

# 1
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1
print("arr_zeros =", arr_zeros)

# 2
arr_h = np.arange(10, 25)
arr_h_reverse = arr_h[::-1]
print("arr_h =", arr_h)
print("arr_h_reverse =", arr_h_reverse)

# 3
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l = arr_k[arr_k != 0]
print("arr_l =", arr_l)

# 4
arr_l2 = np.append(arr_l, [10, 20])
print("arr_l2 =", arr_l2)

# 5
arr_l3 = np.insert(arr_l2, 5, 100)
print("arr_l3 =", arr_l3)

# 6
arr_l4 = np.delete(arr_l3, [0, 1, 2])
print("arr_l4 =", arr_l4)


arr_zeros = [0 0 0 0 1 0 0 0 0 0]
arr_h = [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
arr_h_reverse = [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
arr_l = [1 2 8 2 1 3 5]
arr_l2 = [ 1  2  8  2  1  3  5 10 20]
arr_l3 = [  1   2   8   2   1 100   3   5  10  20]
arr_l4 = [  2   1 100   3   5  10  20]


bài 5

In [1]:
heights = [72, 74, 69, 73, 71, 76, 70, 68, 75, 77, 
           72, 73, 74, 69, 70, 71, 72, 73, 74, 75,
           76, 77, 78, 79, 80, 81, 70, 71, 72, 73,
           74, 75, 76, 77, 78, 79, 80, 81, 70, 71,
           72, 73, 74, 75, 76, 77, 78, 79, 80, 81]

weights = [180, 215, 210, 188, 176, 209, 200, 175, 220, 231,
           190, 200, 210, 180, 178, 185, 190, 195, 200, 210,
           220, 225, 230, 240, 250, 260, 190, 200, 210, 220,
           180, 185, 190, 195, 200, 205, 210, 215, 220, 225,
           230, 235, 240, 245, 250, 255, 260, 265, 270, 275]
with open("heights_1.txt", "w") as f:
    f.write(",".join(map(str, heights)))

with open("weights_1.txt", "w") as f:
    f.write(",".join(map(str, weights)))

print("✅ Đã tạo xong 2 file heights_1.txt và weights_1.txt trong thư mục !")


import numpy as np
with open("heights_1.txt") as f:
    height = [float(x) for x in f.read().split(",")]

with open("weights_1.txt") as f:
    weight = [float(x) for x in f.read().split(",")]
arr_height = np.array(height)
arr_weight = np.array(weight)
# Đổi đơn vị
arr_height_m = arr_height * 0.0254
arr_weight_kg = arr_weight * 0.453592
# BMI
arr_bmi = arr_weight_kg / (arr_height_m ** 2)
n = arr_height_m.size
print("Số phần tử:", n)
if n > 50:
    print("Index 50 -> height:", arr_height_m[50], "m; weight:", arr_weight_kg[50], "kg")
else:
    print(f"Không có index 50 (chỉ có 0..{n-1}). In phần tử cuối thay thế:")
    print("Index", n-1, "-> height:", arr_height_m[-1], "m; weight:", arr_weight_kg[-1], "kg")
print("Các phần tử từ 100 đến 110:", arr_height_m[100:111])
print("BMI < 21:", arr_bmi[arr_bmi < 21])
# Trung bình & lớn nhất/nhỏ nhất
print("Chiều cao TB:", np.mean(arr_height_m))
print("Cân nặng TB:", np.mean(arr_weight_kg))
print("BMI TB:", np.mean(arr_bmi))
print("Chiều cao max/min:", np.max(arr_height_m), "/", np.min(arr_height_m))
print("Cân nặng max/min:", np.max(arr_weight_kg), "/", np.min(arr_weight_kg))

✅ Đã tạo xong 2 file heights_1.txt và weights_1.txt trong thư mục !
Số phần tử: 50
Không có index 50 (chỉ có 0..49). In phần tử cuối thay thế:
Index 49 -> height: 2.0574 m; weight: 124.7378 kg
Các phần tử từ 100 đến 110: []
BMI < 21: []
Chiều cao TB: 1.8953479999999998
Cân nặng TB: 97.40434608
BMI TB: 27.09226111295185
Chiều cao max/min: 2.0574 / 1.7271999999999998
Cân nặng max/min: 124.7378 / 79.3786


bài 6

In [5]:
import numpy as np
#1
arr = np.array([[True, True, True],
                [True, True, True],
                [True, True, True]])
print(arr)
#2
arr_1D = np.array([0,1,2,3,4,5,6,7,8])

arr_2D = arr_1D.reshape(3,3)
print("arr_2D ban đầu:\n", arr_2D)



[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
arr_2D ban đầu:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


bài 7

In [1]:
import numpy as np

# 1. Đọc dữ liệu vào numpy array 2D
np_baseball = np.loadtxt("baseball_2D.txt", dtype=int)
print("Dữ liệu np_baseball:\n", np_baseball)
print("Kiểu dữ liệu:", type(np_baseball))
print("Kích thước:", np_baseball.shape)  
# 2. 
print("Giá trị dòng thứ 50:", np_baseball[49])

# 3. 
np_weight = np_baseball[:, 1]
print("Mảng cân nặng:", np_weight)

# 4. 
print("Chiều cao vận động viên thứ 124:", np_baseball[123, 0], "inch")

# 5. 
print("Chiều cao trung bình:", np.mean(np_baseball[:, 0]), "inch")
print("Cân nặng trung bình:", np.mean(np_baseball[:, 1]), "pound")

# 6.
corr = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])[0, 1]
print("Hệ số tương quan:", corr)

if corr > 0:
    print("→ Chiều cao và cân nặng có tương quan **thuận**: cao hơn → nặng hơn.")
elif corr < 0:
    print("→ Chiều cao và cân nặng có tương quan **nghịch**.")
else:
    print("→ Không có mối liên hệ rõ ràng.")


Dữ liệu np_baseball:
 [[ 74 180]
 [ 74 215]
 [ 72 210]
 [ 72 210]
 [ 73 188]
 [ 69 176]
 [ 69 209]
 [ 71 200]
 [ 76 231]
 [ 71 180]
 [ 73 188]
 [ 73 180]
 [ 74 185]
 [ 74 160]
 [ 69 180]
 [ 70 185]
 [ 72 197]
 [ 73 189]
 [ 75 185]
 [ 78 219]
 [ 79 230]
 [ 76 205]
 [ 74 230]
 [ 76 195]
 [ 72 180]
 [ 71 192]
 [ 75 225]
 [ 77 203]
 [ 74 195]
 [ 73 182]
 [ 74 188]
 [ 78 200]
 [ 73 180]
 [ 75 200]
 [ 73 200]
 [ 75 245]
 [ 75 240]
 [ 74 215]
 [ 69 185]
 [ 71 175]
 [ 74 199]
 [ 73 200]
 [ 73 215]
 [ 76 200]
 [ 74 205]
 [ 74 206]
 [ 70 186]
 [ 72 188]
 [ 77 220]
 [ 74 210]
 [ 70 195]
 [ 74 244]
 [ 75 195]
 [ 73 200]
 [ 75 200]
 [ 76 212]
 [ 76 224]
 [ 78 210]
 [ 74 205]
 [ 74 220]
 [ 76 195]
 [ 77 200]
 [ 81 260]
 [ 78 228]
 [ 75 270]
 [ 77 200]
 [ 75 210]
 [ 76 190]
 [ 74 220]
 [ 72 180]
 [ 72 205]
 [ 75 210]
 [ 73 220]
 [ 73 211]
 [ 73 200]
 [ 70 180]
 [ 70 190]
 [ 70 170]
 [ 76 230]
 [ 68 155]
 [ 71 185]
 [ 72 185]
 [ 75 200]
 [ 75 225]
 [ 75 225]
 [ 75 220]
 [ 68 160]
 [ 74 205]
 [ 78 235]

bài 8

In [6]:

positions = ['GK', 'M', 'GK', 'A', 'D', 'M', 'A', 'D', 'GK', 'M', 'A', 'D', 'M', 'GK', 'D', 'A']
heights = [188, 175, 192, 180, 185, 170, 178, 182, 190, 172, 176, 184, 177, 195, 186, 179]
with open("heights.txt", "w") as f:
    f.write(",".join(map(str, heights)))

with open("positions.txt", "w") as f:
    f.write(",".join(map(str, positions)))

print("✅ Đã tạo xong 2 file heights_1.txt và weights_1.txt trong thư mục !")

import numpy as np
#1
np_heights = np.array(heights)
np_positions = np.array(positions)
print("Kiểu dữ liệu np_heights:", type(np_heights))
print("Kiểu dữ liệu np_positions:", type(np_positions))
#2
gk_heights = np_heights[np_positions == 'GK']
avg_gk = np.mean(gk_heights)
print("Chiều cao trung bình GK:", avg_gk)
#3
non_gk_heights = np_heights[np_positions != 'GK']
avg_non_gk = np.mean(non_gk_heights)
print("Chiều cao trung bình ngoài GK:", avg_non_gk)
#4
player_dtype = np.dtype([('position', 'U5'), ('height', 'f4')])
players = np.array(list(zip(np_positions, np_heights)), dtype=player_dtype)
print(players[:5])
#5
sorted_players = np.sort(players, order='height')
print("Thấp nhất:", sorted_players[0])
print("Cao nhất:", sorted_players[-1])



✅ Đã tạo xong 2 file heights_1.txt và weights_1.txt trong thư mục !
Kiểu dữ liệu np_heights: <class 'numpy.ndarray'>
Kiểu dữ liệu np_positions: <class 'numpy.ndarray'>
Chiều cao trung bình GK: 191.25
Chiều cao trung bình ngoài GK: 178.66666666666666
[('GK', 188.) ('M', 175.) ('GK', 192.) ('A', 180.) ('D', 185.)]
Thấp nhất: ('M', 170.0)
Cao nhất: ('GK', 195.0)


bài 9

In [14]:
import numpy as np

teams = np.array(['Germany', 'Greece', 'England', 'Italy', 'Russia', 'Spain', 'Portugal', 'France'])
goals = np.array([12, 4, 7, 9, 6, 10, 5, 3])
yellow_cards = np.array([5, 7, 6, 4, 3, 2, 5, 6])
red_cards = np.array([1, 0, 2, 1, 0, 1, 0, 1])
shooting_accuracy = np.array([52.5, 43.0, 49.5, 50.2, 45.3, 55.1, 48.0, 46.2])

euro12 = np.zeros(len(teams), dtype=[('Team', 'U20'), 
                                     ('Goals', 'i4'), 
                                     ('Yellow Cards', 'i4'), 
                                     ('Red Cards', 'i4'),
                                     ('Shooting Accuracy', 'f4')])

euro12['Team'] = teams
euro12['Goals'] = goals
euro12['Yellow Cards'] = yellow_cards
euro12['Red Cards'] = red_cards
euro12['Shooting Accuracy'] = shooting_accuracy

print("Type:", type(euro12))
print("Shape:", euro12.shape)
print("Columns:", euro12.dtype.names)


#1
print("\nGoals column:")
print(euro12['Goals'])
#2
print("\nSố đội tham gia:", len(np.unique(euro12['Team'])))

#3
print("\nThông tin DataFrame:")
for name in euro12.dtype.names:
    print(f"{name}: {euro12[name].dtype}, shape: {euro12[name].shape}")

#4
discipline = np.column_stack((euro12['Team'], euro12['Yellow Cards'], euro12['Red Cards']))

# 5
red_cards = discipline[:,2].astype(int)
yellow_cards = discipline[:,1].astype(int)
sorted_indices = np.lexsort((yellow_cards, red_cards))[::-1]  
discipline_sorted = discipline[sorted_indices]
print("\nDiscipline sorted:")
print(discipline_sorted)

#6a
avg_yellow = np.mean(euro12['Yellow Cards'])
print("\nTrung bình Yellow Cards:", avg_yellow)

#6b
teams_more_than_6_goals = euro12[euro12['Goals'] > 6]['Team']
print("\nĐội ghi hơn 6 bàn thắng:")
print(teams_more_than_6_goals)

#7
teams_start_G = [team for team in euro12['Team'] if team.startswith('G')]
print("\nĐội bắt đầu bằng 'G':")
print(teams_start_G)

#8
print("\n7 cột đầu:")
first_7_cols = [euro12[name] for name in euro12.dtype.names[:7]]
print(np.column_stack(first_7_cols))

#9
print("\nTất cả cột trừ 3 cột cuối:")
cols_except_last3 = [euro12[name] for name in euro12.dtype.names[:-3]]
print(np.column_stack(cols_except_last3))

#10
teams_mask = np.isin(euro12['Team'], ['England', 'Italy', 'Russia'])
selected_data = euro12[teams_mask]
print("\nCác cột 'Team', 'Goals', 'Shooting Accuracy' từ 3 đội:")
for row in selected_data:
    print(row['Team'], row['Goals'], row['Shooting Accuracy'])

#11
print("\nChỉ 'Team' và 'Shooting Accuracy' từ 3 đội:")
for row in selected_data:
    print(row['Team'], row['Shooting Accuracy'])



Type: <class 'numpy.ndarray'>
Shape: (8,)
Columns: ('Team', 'Goals', 'Yellow Cards', 'Red Cards', 'Shooting Accuracy')

Goals column:
[12  4  7  9  6 10  5  3]

Số đội tham gia: 8

Thông tin DataFrame:
Team: <U20, shape: (8,)
Goals: int32, shape: (8,)
Yellow Cards: int32, shape: (8,)
Red Cards: int32, shape: (8,)
Shooting Accuracy: float32, shape: (8,)

Discipline sorted:
[['England' '6' '2']
 ['France' '6' '1']
 ['Germany' '5' '1']
 ['Italy' '4' '1']
 ['Spain' '2' '1']
 ['Greece' '7' '0']
 ['Portugal' '5' '0']
 ['Russia' '3' '0']]

Trung bình Yellow Cards: 4.75

Đội ghi hơn 6 bàn thắng:
['Germany' 'England' 'Italy' 'Spain']

Đội bắt đầu bằng 'G':
[np.str_('Germany'), np.str_('Greece')]

7 cột đầu:
[['Germany' '12' '5' '1' '52.5']
 ['Greece' '4' '7' '0' '43.0']
 ['England' '7' '6' '2' '49.5']
 ['Italy' '9' '4' '1' '50.2']
 ['Russia' '6' '3' '0' '45.3']
 ['Spain' '10' '2' '1' '55.1']
 ['Portugal' '5' '5' '0' '48.0']
 ['France' '3' '6' '1' '46.2']]

Tất cả cột trừ 3 cột cuối:
[['Germany'

bài 10

In [15]:
import numpy as np

countries = np.array(['USA','France','Germany','India','Nigeria','Brazil','China','Australia','Russia','Italy'])
beer_servings = np.array([249, 127, 346, 12, 25, 245, 45, 311, 200, 175])
spirit_servings = np.array([158, 120, 70, 45, 40, 130, 100, 150, 210, 90])
wine_servings = np.array([50, 220, 175, 10, 20, 70, 15, 180, 90, 200])
total_litres_of_pure_alcohol = np.array([8.5, 12.3, 10.5, 3.2, 2.8, 7.0, 4.1, 11.5, 9.0, 10.8])
continent = np.array(['North America','Europe','Europe','Asia','Africa','South America','Asia','Oceania','Europe','Europe'])


drink = np.zeros(len(countries), dtype=[('country','U20'),
                                        ('beer_servings','i4'),
                                        ('spirit_servings','i4'),
                                        ('wine_servings','i4'),
                                        ('total_litres_of_pure_alcohol','f4'),
                                        ('continent','U20')])

drink['country'] = countries
drink['beer_servings'] = beer_servings
drink['spirit_servings'] = spirit_servings
drink['wine_servings'] = wine_servings
drink['total_litres_of_pure_alcohol'] = total_litres_of_pure_alcohol
drink['continent'] = continent

#1
print("Type:", type(drink))
print("Shape:", drink.shape)
print("Columns:", drink.dtype.names)

print("\n5 dòng đầu:")
print(drink[:5])

print("\n5 dòng cuối:")
print(drink[-5:])

#2
continents = np.unique(drink['continent'])
avg_beer_by_continent = {c: drink['beer_servings'][drink['continent']==c].mean() for c in continents}
print("\nBia tiêu thụ trung bình theo châu lục:")
for k,v in avg_beer_by_continent.items():
    print(k, ":", v)

#3
print("\nThống kê rượu vang theo châu lục:")
for c in continents:
    wine = drink['wine_servings'][drink['continent']==c]
    print(f"{c}: mean={wine.mean():.2f}, median={np.median(wine)}, min={wine.min()}, max={wine.max()}, std={wine.std():.2f}")

# =========================
# 4. Trung bình beer + wine theo châu lục
# =========================
print("\nTrung bình bia và rượu vang theo châu lục:")
for c in continents:
    mask = drink['continent']==c
    mean_beer = drink['beer_servings'][mask].mean()
    mean_wine = drink['wine_servings'][mask].mean()
    print(f"{c}: beer={mean_beer:.2f}, wine={mean_wine:.2f}")

#5
print("\nTrung vị bia và rượu vang theo châu lục:")
for c in continents:
    mask = drink['continent']==c
    median_beer = np.median(drink['beer_servings'][mask])
    median_wine = np.median(drink['wine_servings'][mask])
    print(f"{c}: beer={median_beer}, wine={median_wine}")

#6
print("\nTiêu thụ rượu mạnh theo châu lục:")
for c in continents:
    spirit = drink['spirit_servings'][drink['continent']==c]
    print(f"{c}: mean={spirit.mean():.2f}, max={spirit.max()}, min={spirit.min()}")

#7
sorted_indices = np.argsort(drink['beer_servings'])
sorted_drink = drink[sorted_indices]

print("\n5 quốc gia uống bia ít nhất:")
print(sorted_drink[:5][['country','beer_servings']])

print("\n5 quốc gia uống bia nhiều nhất:")
print(sorted_drink[-5:][['country','beer_servings']])


Type: <class 'numpy.ndarray'>
Shape: (10,)
Columns: ('country', 'beer_servings', 'spirit_servings', 'wine_servings', 'total_litres_of_pure_alcohol', 'continent')

5 dòng đầu:
[('USA', 249, 158,  50,  8.5, 'North America')
 ('France', 127, 120, 220, 12.3, 'Europe')
 ('Germany', 346,  70, 175, 10.5, 'Europe')
 ('India',  12,  45,  10,  3.2, 'Asia')
 ('Nigeria',  25,  40,  20,  2.8, 'Africa')]

5 dòng cuối:
[('Brazil', 245, 130,  70,  7. , 'South America')
 ('China',  45, 100,  15,  4.1, 'Asia')
 ('Australia', 311, 150, 180, 11.5, 'Oceania')
 ('Russia', 200, 210,  90,  9. , 'Europe')
 ('Italy', 175,  90, 200, 10.8, 'Europe')]

Bia tiêu thụ trung bình theo châu lục:
Africa : 25.0
Asia : 28.5
Europe : 212.0
North America : 249.0
Oceania : 311.0
South America : 245.0

Thống kê rượu vang theo châu lục:
Africa: mean=20.00, median=20.0, min=20, max=20, std=0.00
Asia: mean=12.50, median=12.5, min=10, max=15, std=2.50
Europe: mean=171.25, median=187.5, min=90, max=220, std=49.54
North America: me